[2024-12-21T21:11:08.316+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:11:08.318+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:11:08.323+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:11:08.322+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:11:08.376+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:11:08.367+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:11:08.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:11:08.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.124 seconds
[2024-12-21T21:11:39.259+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:11:39.261+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:11:39.265+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:11:39.264+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:11:39.304+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:11:39.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:11:39.308+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:11:39.352+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.103 seconds
[2024-12-21T21:12:10.021+0000] {processor.py:186} INFO - Started process (PID=806) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:12:10.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:12:10.028+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:12:10.027+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:12:10.060+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:12:10.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:12:10.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:12:10.104+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.097 seconds
[2024-12-21T21:12:40.727+0000] {processor.py:186} INFO - Started process (PID=1102) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:12:40.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:12:40.736+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:12:40.735+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:12:40.768+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:12:40.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:12:40.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:12:40.807+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.098 seconds
[2024-12-21T21:13:10.988+0000] {processor.py:186} INFO - Started process (PID=1398) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:13:10.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:13:10.994+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:13:10.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:13:11.031+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:13:11.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:13:11.034+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:13:11.119+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.143 seconds
[2024-12-21T21:13:41.959+0000] {processor.py:186} INFO - Started process (PID=1694) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:13:41.961+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:13:41.966+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:13:41.965+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:13:42.009+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:13:41.999+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:13:42.013+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:13:42.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.133 seconds
[2024-12-21T21:14:12.976+0000] {processor.py:186} INFO - Started process (PID=1990) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:14:12.978+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:14:12.983+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:14:12.982+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:14:13.025+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:14:13.017+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:14:13.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:14:13.090+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.128 seconds
[2024-12-21T21:14:43.286+0000] {processor.py:186} INFO - Started process (PID=2286) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:14:43.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:14:43.292+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:14:43.292+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:14:43.330+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:14:43.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:14:43.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:14:43.393+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.120 seconds
[2024-12-21T21:15:13.569+0000] {processor.py:186} INFO - Started process (PID=2582) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:15:13.571+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:15:13.575+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:15:13.575+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:15:13.622+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:15:13.615+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:15:13.625+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:15:13.686+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.129 seconds
[2024-12-21T21:15:44.345+0000] {processor.py:186} INFO - Started process (PID=2878) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:15:44.347+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:15:44.352+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:15:44.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:15:44.394+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:15:44.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:15:44.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:15:44.457+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.123 seconds
[2024-12-21T21:16:17.011+0000] {processor.py:186} INFO - Started process (PID=3174) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:16:17.013+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:16:17.019+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:16:17.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:16:17.057+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:16:17.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:16:17.061+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:16:17.134+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.139 seconds
[2024-12-21T21:16:47.908+0000] {processor.py:186} INFO - Started process (PID=3417) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:16:47.910+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:16:47.916+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:16:47.915+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:16:47.954+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:16:47.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:16:47.957+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:16:48.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.110 seconds
[2024-12-21T21:17:18.738+0000] {processor.py:186} INFO - Started process (PID=3695) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:17:18.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:17:18.744+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:17:18.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:17:18.782+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:17:18.772+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:17:18.786+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:17:18.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.119 seconds
[2024-12-21T21:17:49.877+0000] {processor.py:186} INFO - Started process (PID=3954) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:17:49.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:17:49.886+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:17:49.885+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:17:49.924+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:17:49.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:17:49.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:17:49.974+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.111 seconds
[2024-12-21T21:18:20.651+0000] {processor.py:186} INFO - Started process (PID=4240) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:18:20.654+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:18:20.659+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:18:20.658+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:18:20.701+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:18:20.690+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:18:20.704+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:18:20.757+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.119 seconds
[2024-12-21T21:18:51.303+0000] {processor.py:186} INFO - Started process (PID=4533) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:18:51.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:18:51.312+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:18:51.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:18:51.357+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:18:51.349+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:18:51.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:18:51.408+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.122 seconds
[2024-12-21T21:19:21.540+0000] {processor.py:186} INFO - Started process (PID=4829) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:19:21.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:19:21.547+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:19:21.547+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:19:21.589+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:19:21.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:19:21.593+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:19:21.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.126 seconds
[2024-12-21T21:19:51.951+0000] {processor.py:186} INFO - Started process (PID=5123) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:19:51.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:19:51.958+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:19:51.958+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:19:52.002+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:19:51.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:19:52.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:19:52.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.132 seconds
[2024-12-21T21:20:22.239+0000] {processor.py:186} INFO - Started process (PID=5413) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:20:22.240+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:20:22.244+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:20:22.244+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:20:22.274+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:20:22.268+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:20:22.277+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:20:22.341+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.114 seconds
[2024-12-21T21:20:52.514+0000] {processor.py:186} INFO - Started process (PID=5701) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:20:52.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:20:52.522+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:20:52.521+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:20:52.560+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:20:52.552+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:20:52.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:20:52.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.110 seconds
[2024-12-21T21:21:23.450+0000] {processor.py:186} INFO - Started process (PID=5998) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:21:23.452+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:21:23.458+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:21:23.457+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:21:23.508+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:21:23.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:21:23.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:21:23.559+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.122 seconds
[2024-12-21T21:21:54.307+0000] {processor.py:186} INFO - Started process (PID=6294) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:21:54.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:21:54.316+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:21:54.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:21:54.350+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:21:54.343+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:21:54.353+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:21:54.396+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.104 seconds
[2024-12-21T21:22:24.609+0000] {processor.py:186} INFO - Started process (PID=6590) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:22:24.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:22:24.616+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:22:24.615+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:22:24.658+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:22:24.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:22:24.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:22:24.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.123 seconds
[2024-12-21T21:22:55.093+0000] {processor.py:186} INFO - Started process (PID=6886) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:22:55.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:22:55.099+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:22:55.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:22:55.145+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:22:55.136+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:22:55.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:22:55.209+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.127 seconds
[2024-12-21T21:23:25.373+0000] {processor.py:186} INFO - Started process (PID=7183) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:23:25.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:23:25.380+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:23:25.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:23:25.424+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:23:25.415+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:23:25.427+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:23:25.489+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.127 seconds
[2024-12-21T21:23:55.863+0000] {processor.py:186} INFO - Started process (PID=7479) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:23:55.865+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:23:55.870+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:23:55.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:23:55.915+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:23:55.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:23:55.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:23:55.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.129 seconds
[2024-12-21T21:24:26.554+0000] {processor.py:186} INFO - Started process (PID=7775) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:24:26.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:24:26.561+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:24:26.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:24:26.609+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:24:26.599+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:24:26.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:24:26.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.113 seconds
[2024-12-21T21:26:27.275+0000] {processor.py:186} INFO - Started process (PID=207) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:26:27.277+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:26:27.282+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:26:27.282+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:26:27.315+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:26:27.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:26:27.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:26:27.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.100 seconds
[2024-12-21T21:26:57.873+0000] {processor.py:186} INFO - Started process (PID=503) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:26:57.875+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:26:57.880+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:26:57.879+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:26:57.910+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:26:57.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:26:57.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:26:57.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.109 seconds
[2024-12-21T21:27:28.489+0000] {processor.py:186} INFO - Started process (PID=799) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:27:28.492+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:27:28.498+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:27:28.497+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:27:28.532+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:27:28.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:27:28.535+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:27:28.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.106 seconds
[2024-12-21T21:27:58.943+0000] {processor.py:186} INFO - Started process (PID=1095) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:27:58.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:27:58.949+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:27:58.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:27:58.983+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:27:58.976+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:27:58.986+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:27:59.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.093 seconds
[2024-12-21T21:28:29.778+0000] {processor.py:186} INFO - Started process (PID=1397) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:28:29.780+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:28:29.785+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:28:29.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:28:29.821+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:28:29.813+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:28:29.825+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:28:29.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.100 seconds
[2024-12-21T21:29:00.656+0000] {processor.py:186} INFO - Started process (PID=1693) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:29:00.658+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:29:00.664+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:29:00.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:29:00.706+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:29:00.698+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:29:00.711+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:29:00.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.118 seconds
[2024-12-21T21:29:31.283+0000] {processor.py:186} INFO - Started process (PID=1990) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:29:31.286+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:29:31.290+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:29:31.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:29:31.324+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:29:31.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:29:31.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:29:31.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.101 seconds
[2024-12-21T21:30:01.875+0000] {processor.py:186} INFO - Started process (PID=2286) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:30:01.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:30:01.882+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:30:01.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:30:01.925+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:30:01.918+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:30:01.928+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:30:01.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.112 seconds
[2024-12-21T21:30:32.511+0000] {processor.py:186} INFO - Started process (PID=2582) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:30:32.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:30:32.517+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:30:32.517+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:30:32.553+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:30:32.546+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:30:32.556+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:30:32.596+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.099 seconds
[2024-12-21T21:31:02.855+0000] {processor.py:186} INFO - Started process (PID=2878) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:31:02.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:31:02.863+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:31:02.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:31:02.893+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:31:02.886+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:31:02.896+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:31:02.935+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.093 seconds
[2024-12-21T21:31:33.140+0000] {processor.py:186} INFO - Started process (PID=3175) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:31:33.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:31:33.147+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:31:33.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:31:33.185+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:31:33.177+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:31:33.188+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:31:33.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.125 seconds
[2024-12-21T21:32:04.020+0000] {processor.py:186} INFO - Started process (PID=3471) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:32:04.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:32:04.026+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:32:04.026+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:32:04.063+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:32:04.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:32:04.066+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:32:04.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.122 seconds
[2024-12-21T21:32:34.394+0000] {processor.py:186} INFO - Started process (PID=3767) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:32:34.397+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:32:34.402+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:32:34.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:32:34.434+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:32:34.426+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:32:34.437+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:32:34.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.115 seconds
[2024-12-21T21:33:05.459+0000] {processor.py:186} INFO - Started process (PID=4063) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:33:05.461+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:33:05.465+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:33:05.464+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:33:05.503+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:33:05.496+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:33:05.506+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:33:05.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.097 seconds
[2024-12-21T21:33:36.212+0000] {processor.py:186} INFO - Started process (PID=4359) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:33:36.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:33:36.218+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:33:36.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:33:36.256+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:33:36.248+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:33:36.259+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:33:36.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.096 seconds
[2024-12-21T21:34:07.191+0000] {processor.py:186} INFO - Started process (PID=4655) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:34:07.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:34:07.199+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:34:07.198+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:34:07.234+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:34:07.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:34:07.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:34:07.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.117 seconds
[2024-12-21T21:34:37.653+0000] {processor.py:186} INFO - Started process (PID=4952) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:34:37.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:34:37.668+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:34:37.668+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:34:37.725+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:34:37.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:34:37.728+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:34:37.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.154 seconds
[2024-12-21T21:35:08.540+0000] {processor.py:186} INFO - Started process (PID=5213) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:35:08.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:35:08.547+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:35:08.546+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:35:08.584+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:35:08.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:35:08.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:35:08.626+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.096 seconds
[2024-12-21T21:35:39.774+0000] {processor.py:186} INFO - Started process (PID=5492) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:35:39.776+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:35:39.780+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:35:39.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:35:39.814+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:35:39.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:35:39.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:35:39.857+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.096 seconds
[2024-12-21T21:36:10.244+0000] {processor.py:186} INFO - Started process (PID=5778) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:36:10.246+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:36:10.250+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:36:10.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:36:10.290+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:36:10.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:36:10.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:36:10.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.127 seconds
[2024-12-21T21:36:40.703+0000] {processor.py:186} INFO - Started process (PID=6069) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:36:40.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:36:40.709+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:36:40.708+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:36:40.740+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:36:40.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:36:40.743+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:36:40.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.090 seconds
[2024-12-21T21:37:10.890+0000] {processor.py:186} INFO - Started process (PID=6360) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:37:10.892+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:37:10.896+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:37:10.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:37:10.929+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:37:10.923+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:37:10.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:37:10.972+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.093 seconds
[2024-12-21T21:37:41.268+0000] {processor.py:186} INFO - Started process (PID=6651) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:37:41.270+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:37:41.275+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:37:41.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:37:41.316+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:37:41.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:37:41.319+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:37:41.368+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.110 seconds
[2024-12-21T21:38:11.526+0000] {processor.py:186} INFO - Started process (PID=6937) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:38:11.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:38:11.534+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:38:11.533+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:38:11.575+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:38:11.563+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:38:11.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:38:11.624+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.110 seconds
[2024-12-21T21:38:42.317+0000] {processor.py:186} INFO - Started process (PID=7225) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:38:42.320+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:38:42.327+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:38:42.326+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:38:42.375+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:38:42.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:38:42.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:38:42.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.140 seconds
[2024-12-21T21:39:12.583+0000] {processor.py:186} INFO - Started process (PID=7521) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:39:12.588+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:39:12.594+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:39:12.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:39:12.629+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:39:12.621+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:39:12.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:39:12.677+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.107 seconds
[2024-12-21T21:39:42.991+0000] {processor.py:186} INFO - Started process (PID=7817) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:39:42.995+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:39:43.000+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:39:42.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:39:43.034+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:39:43.026+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:39:43.038+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:39:43.110+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.134 seconds
[2024-12-21T21:40:13.547+0000] {processor.py:186} INFO - Started process (PID=8113) to work on /opt/airflow/dags/customer_activity.py
[2024-12-21T21:40:13.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/customer_activity.py for tasks to queue
[2024-12-21T21:40:13.556+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:40:13.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:40:13.606+0000] {logging_mixin.py:190} INFO - [2024-12-21T21:40:13.594+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/customer_activity.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/customer_activity.py", line 7, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
[2024-12-21T21:40:13.612+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/customer_activity.py
[2024-12-21T21:40:13.694+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/customer_activity.py took 0.161 seconds
